require("dotenv").config();
const express=require("express");
const crypto=require("crypto");
const db=require("./database");
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||"admin123";
const app=express();
app.use(express.urlencoded({extended:true}));
app.use(express.json());
function authMiddleware(req,res,next){
  if(req.path.startsWith("/p/")||req.path==="/login"||req.path==="/logout") return next();
  const cookie=req.headers.cookie||"";
  if(cookie.includes("pf_auth=ok")) return next();
  return res.redirect("/login");
}
app.use(authMiddleware);
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function getSettings(){return db.prepare("SELECT * FROM settings LIMIT 1").get();}
function layout(t,c,a=""){
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t} - PRO</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet"><style>body{font-family:'Inter',sans-serif;background:#f5f7fb;color:#0f172a}.sidebar{position:fixed;top:0;left:0;bottom:0;width:280px;background:#0f172a;padding:24px;display:flex;flex-direction:column;z-index:1000}.brand{color:#fff;font-size:22px;font-weight:800;display:flex;align-items:center;gap:10px;margin-bottom:32px}.brand i{color:#6366f1}.nav-link{color:#94a3b8;padding:12px 14px;border-radius:10px;margin-bottom:6px;display:flex;align-items:center;gap:12px;font-weight:600;font-size:14px;text-decoration:none}.nav-link:hover{background:#1e293b;color:#fff}.nav-link.active{background:#6366f1;color:#fff}.main{margin-left:280px;min-height:100vh}.topbar{background:#fff;border-bottom:1px solid #e2e8f0;padding:18px 36px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:100}.card-pro{border:0;border-radius:18px;box-shadow:0 10px 30px rgba(15,23,42,.06);background:#fff}.stat-icon{width:48px;height:48px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:20px}.btn-primary{background:#6366f1;border:0;border-radius:10px;padding:11px 20px;font-weight:700}.btn-primary:hover{background:#4f46e5}</style></head><body><div class="sidebar"><div class="brand"><i class="bi bi-lightning-charge-fill"></i> ProposalForge PRO</div><a class="nav-link ${a==='dash'?'active':''}" href="/"><i class="bi bi-grid-1x2-fill"></i> Dashboard</a><a class="nav-link ${a==='clients'?'active':''}" href="/clients"><i class="bi bi-people-fill"></i> Clients</a><a class="nav-link ${a==='services'?'active':''}" href="/services"><i class="bi bi-box-seam-fill"></i> Services</a><a class="nav-link ${a==='proposals'?'active':''}" href="/proposals"><i class="bi bi-file-earmark-text-fill"></i> Proposals</a><a class="nav-link ${a==='settings'?'active':''}" href="/settings"><i class="bi bi-gear-fill"></i> Settings</a><div style="margin-top:auto"><a class="nav-link" href="/logout"><i class="bi bi-box-arrow-left"></i> Logout</a></div></div><div class="main"><div class="topbar"><div><h5 class="m-0 fw-bold">${t}</h5><small class="text-muted">ProposalForge PRO</small></div><div><span class="badge bg-light text-dark border"><i class="bi bi-shield-check"></i> Licensed</span></div></div><div style="padding:32px">${c}</div></div></body></html>`;
}
app.get("/",(req,res)=>{const s=getSettings();const cc=db.prepare("SELECT COUNT(*) c FROM clients").get().c;const sc=db.prepare("SELECT COUNT(*) c FROM services").get().c;const pc=db.prepare("SELECT COUNT(*) c FROM proposals").get().c;res.send(layout("Dashboard",`<div class="row g-4 mb-4"><div class="col-md-4"><div class="card-pro p-4"><div class="d-flex justify-content-between align-items-center"><div><small class="text-muted fw-bold">CLIENTS</small><div class="fs-1 fw-bolder">${cc}</div></div><div class="stat-icon bg-primary bg-opacity-10 text-primary"><i class="bi bi-people"></i></div></div></div></div><div class="col-md-4"><div class="card-pro p-4"><div class="d-flex justify-content-between align-items-center"><div><small class="text-muted fw-bold">SERVICES</small><div class="fs-1 fw-bolder">${sc}</div></div><div class="stat-icon bg-success bg-opacity-10 text-success"><i class="bi bi-box-seam"></i></div></div></div></div><div class="col-md-4"><div class="card-pro p-4"><div class="d-flex justify-content-between align-items-center"><div><small class="text-muted fw-bold">PROPOSALS</small><div class="fs-1 fw-bolder">${pc}</div></div><div class="stat-icon bg-warning bg-opacity-10 text-warning"><i class="bi bi-file-earmark-text"></i></div></div></div></div></div><div class="card-pro p-4"><h6 class="fw-bold">Welcome ${escapeHtml(s.company_name)}</h6><p class="text-muted small">Your PRO version is ready to sell.</p><a href="/proposals/new" class="btn btn-primary">+ New Proposal</a></div>`,"dash"));});
app.get("/clients",(req,res)=>{const cs=db.prepare("SELECT * FROM clients ORDER BY id DESC").all();res.send(layout("Clients",`<div class="card-pro p-4"><div class="d-flex justify-content-between mb-4"><h4 class="fw-bold m-0">Clients</h4><a class="btn btn-primary" href="/clients/new">Add Client</a></div><table class="table"><tr><th>Name</th><th>Email</th><th>Company</th><th></th></tr>${cs.map(x=>`<tr><td><a href="/clients/${x.id}" class="fw-bold">${escapeHtml(x.name)}</a></td><td>${escapeHtml(x.email)}</td><td>${escapeHtml(x.company)}</td><td><a href="/clients/${x.id}/delete">Delete</a></td></tr>`).join("")}</table></div>`,"clients"));});
app.get("/clients/new",(req,res)=>{res.send(layout("Add Client",`<div class="card-pro p-4" style="max-width:640px"><h4 class="fw-bold">Add Client</h4><form method="POST" action="/clients"><input class="form-control mb-2" name="name" required placeholder="Name"><input class="form-control mb-2" name="email" placeholder="Email"><input class="form-control mb-2" name="company" placeholder="Company"><input class="form-control mb-2" name="phone" placeholder="Phone"><button class="btn btn-primary" type="submit">Save</button></form></div>`,"clients"));});
app.post("/clients",(req,res)=>{db.prepare("INSERT INTO clients (name,email,phone,company) VALUES (?,?,?,?)").run(req.body.name,req.body.email,req.body.phone,req.body.company);res.redirect("/clients");});
app.get("/clients/:id",(req,res)=>{const cl=db.prepare("SELECT * FROM clients WHERE id=?").get(req.params.id);if(!cl) return res.status(404).send("Not found");res.send(layout(cl.name,`<div class="card-pro p-4"><h3 class="fw-bold">${escapeHtml(cl.name)}</h3><p>${escapeHtml(cl.email)}</p><a class="btn btn-primary" href="/clients/${cl.id}/edit">Edit</a></div>`,"clients"));});
app.get("/clients/:id/edit",(req,res)=>{const cl=db.prepare("SELECT * FROM clients WHERE id=?").get(req.params.id);res.send(layout("Edit",`<div class="card-pro p-4"><form method="POST" action="/clients/${cl.id}/edit"><input class="form-control mb-2" name="name" value="${escapeHtml(cl.name)}"><input class="form-control mb-2" name="email" value="${escapeHtml(cl.email)}"><input class="form-control mb-2" name="company" value="${escapeHtml(cl.company)}"><button class="btn btn-primary" type="submit">Update</button></form></div>`,"clients"));});
app.post("/clients/:id/edit",(req,res)=>{db.prepare("UPDATE clients SET name=?, email=?, company=?, updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.name,req.body.email,req.body.company,req.params.id);res.redirect("/clients/"+req.params.id);});
app.get("/clients/:id/delete",(req,res)=>{db.prepare("DELETE FROM clients WHERE id=?").run(req.params.id);res.redirect("/clients");});
app.get("/services",(req,res)=>{const sv=db.prepare("SELECT * FROM services ORDER BY id DESC").all();res.send(layout("Services",`<div class="card-pro p-4"><div class="d-flex justify-content-between mb-4"><h4 class="fw-bold m-0">Services</h4><a class="btn btn-primary" href="/services/new">Add Service</a></div><div class="row g-3">${sv.map(s=>`<div class="col-md-4"><div class="card p-3"><h6 class="fw-bold">${escapeHtml(s.name)}</h6><p>$${s.price}</p><a href="/services/${s.id}/edit">Edit</a> | <a href="/services/${s.id}/delete">Delete</a></div></div>`).join("")}</div></div>`,"services"));});
app.get("/services/new",(req,res)=>{res.send(layout("Add Service",`<div class="card-pro p-4" style="max-width:640px"><h4>Add Service</h4><form method="POST" action="/services"><input class="form-control mb-2" name="name" required placeholder="Name"><input type="number" step="0.01" class="form-control mb-2" name="price" required placeholder="Price"><textarea class="form-control mb-2" name="description"></textarea><button class="btn btn-primary" type="submit">Save</button></form></div>`,"services"));});
app.post("/services",(req,res)=>{db.prepare("INSERT INTO services (name, description, price) VALUES (?,?,?)").run(req.body.name,req.body.description,Number(req.body.price)||0);res.redirect("/services");});
app.get("/services/:id/edit",(req,res)=>{const s=db.prepare("SELECT * FROM services WHERE id=?").get(req.params.id);res.send(layout("Edit",`<div class="card-pro p-4"><form method="POST" action="/services/${s.id}/edit"><input class="form-control mb-2" name="name" value="${escapeHtml(s.name)}"><input class="form-control mb-2" name="price" value="${s.price}"><textarea class="form-control mb-2" name="description">${escapeHtml(s.description)}</textarea><button class="btn btn-primary" type="submit">Update</button></form></div>`,"services"));});
app.post("/services/:id/edit",(req,res)=>{db.prepare("UPDATE services SET name=?, price=?, description=? WHERE id=?").run(req.body.name,Number(req.body.price)||0,req.body.description,req.params.id);res.redirect("/services");});
app.get("/services/:id/delete",(req,res)=>{db.prepare("DELETE FROM services WHERE id=?").run(req.params.id);res.redirect("/services");});
app.get("/proposals",(req,res)=>{const ps=db.prepare("SELECT p.*,c.name as client_name FROM proposals p JOIN clients c ON c.id=p.client_id ORDER BY p.id DESC").all();res.send(layout("Proposals",`<div class="card-pro p-4"><div class="d-flex justify-content-between mb-3"><h4>Proposals</h4><a class="btn btn-primary" href="/proposals/new">New</a></div><table class="table"><tr><th>Title</th><th>Client</th><th>Link</th></tr>${ps.map(p=>`<tr><td><a href="/proposals/${p.id}">${escapeHtml(p.title)}</a></td><td>${escapeHtml(p.client_name)}</td><td><a href="/p/${p.public_token}" target="_blank">View</a></td></tr>`).join("")}</table></div>`,"proposals"));});
app.get("/proposals/new",(req,res)=>{const cs=db.prepare("SELECT * FROM clients").all();res.send(layout("New Proposal",`<div class="card-pro p-4"><form method="POST" action="/proposals"><select class="form-select mb-2" name="client_id">${cs.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join("")}</select><input class="form-control mb-2" name="title" required placeholder="Title"><button class="btn btn-primary" type="submit">Create</button></form></div>`,"proposals"));});
app.post("/proposals",(req,res)=>{const token=crypto.randomBytes(16).toString("hex");const info=db.prepare("INSERT INTO proposals (client_id,title,public_token) VALUES (?,?,?)").run(req.body.client_id,req.body.title,token);res.redirect("/proposals/"+info.lastInsertRowid);});
app.get("/proposals/:id",(req,res)=>{const p=db.prepare("SELECT p.*,c.name as client_name FROM proposals p JOIN clients c ON c.id=p.client_id WHERE p.id=?").get(req.params.id);const items=db.prepare("SELECT * FROM proposal_items WHERE proposal_id=?").all(req.params.id);const sv=db.prepare("SELECT * FROM services").all();const settings=getSettings();res.send(layout(p.title,`<div class="card-pro p-4"><h4>${escapeHtml(p.title)} for ${escapeHtml(p.client_name)}</h4><a href="/p/${p.public_token}" target="_blank">Public link</a><form method="POST" action="/proposals/${p.id}/items" class="mt-3"><div class="row g-2"><div class="col-6"><select id="svc" class="form-select"><option value="">Catalog</option>${sv.map(s=>`<option data-price="${s.price}" value="${escapeHtml(s.name)}">${escapeHtml(s.name)}</option>`).join("")}</select></div><div class="col-3"><input id="in" class="form-control" name="name" required placeholder="Item"></div><div class="col-2"><input id="pr" type="number" step="0.01" class="form-control" name="unit_price" required placeholder="Price"></div><div class="col-1"><button class="btn btn-primary w-100">+</button></div></div></form><script>document.getElementById('svc').addEventListener('change',e=>{const o=e.target.selectedOptions[0];if(o){document.getElementById('in').value=o.value;document.getElementById('pr').value=o.dataset.price;}})</script><table class="table mt-3"><tr><th>Item</th><th>Price</th></tr>${items.map(i=>`<tr><td>${escapeHtml(i.name)}</td><td>${settings.currency_symbol}${i.unit_price}</td></tr>`).join("")}</table></div>`,"proposals"));});
app.post("/proposals/:id/items",(req,res)=>{db.prepare("INSERT INTO proposal_items (proposal_id,name,unit_price,quantity) VALUES (?,?,?,1)").run(req.params.id,req.body.name,Number(req.body.unit_price)||0);res.redirect("/proposals/"+req.params.id);});
app.get("/p/:token",(req,res)=>{const proposal=db.prepare("SELECT p.*,c.name as client_name FROM proposals p JOIN clients c ON c.id=p.client_id WHERE public_token=?").get(req.params.token);if(!proposal)return res.status(404).send("Not found");const items=db.prepare("SELECT * FROM proposal_items WHERE proposal_id=?").all(proposal.id);const s=getSettings();res.send(`<html><head><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body><div class="container py-5"><div class="card p-5"><h2>${escapeHtml(proposal.title)}</h2><p>For ${escapeHtml(proposal.client_name)}</p><table class="table">${items.map(i=>`<tr><td>${escapeHtml(i.name)}</td><td>${s.currency_symbol}${i.unit_price}</td></tr>`).join("")}</table></div></div></body></html>`);});
app.get("/login",(req,res)=>{res.send(`<html><head><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#0f172a;display:flex;align-items:center;justify-content:center;min-height:100vh}</style></head><body><div class="card p-5" style="width:400px;border-radius:20px"><h3>ProposalForge PRO</h3><form method="POST" action="/login"><input type="password" name="password" class="form-control my-3" required><button class="btn btn-dark w-100" type="submit">Login</button></form></div></body></html>`);});
app.post("/login",(req,res)=>{if(req.body.password===ADMIN_PASSWORD){res.setHeader("Set-Cookie","pf_auth=ok; Path=/; HttpOnly");return res.redirect("/");}res.send("Wrong <a href='/login'>back</a>");});
app.get("/logout",(req,res)=>{res.setHeader("Set-Cookie","pf_auth=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/");res.redirect("/login");});
app.get("/settings",(req,res)=>{const s=getSettings();res.send(layout("Settings",`<div class="card-pro p-4"><h4>Settings</h4><form method="POST" action="/settings"><input class="form-control mb-2" name="company_name" value="${escapeHtml(s.company_name)}"><input class="form-control mb-2" name="company_email" value="${escapeHtml(s.company_email)}"><button class="btn btn-primary" type="submit">Save</button></form></div>`,"settings"));});
app.post("/settings",(req,res)=>{db.prepare("UPDATE settings SET company_name=?,company_email=?").run(req.body.company_name,req.body.company_email);res.redirect("/settings");});
module.exports=app;